# Generated by Django 6.0.1 on 2026-02-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='research_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('research_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.researchlog')),
            ],
        ),
    ]
