# Generated by Django 6.0.1 on 2026-02-20 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_multitag_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchlog',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
