# Generated by Django 6.0.2 on 2026-02-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_researchlog_created_by_alter_researchlog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlog',
            name='translated_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchlog',
            name='translated_language',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
