# Generated by Django 6.0.2 on 2026-02-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_researchlog_translated_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlog',
            name='translated_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
